
# Makefile
#

default: build

build: build-pep-XXX

build-pep-XXX:
	# ./pep-XXX-linked-data-json-ld-rdf-rdfa.rst > HTML
	rst2html.py ./pep-XXX-linked-data-json-ld-rdf-rdfa.rst > pep-XXX-linked-data-json-ld-rdf-rdfa.rst.html

open:
	web ./pep-XXX-linked-data-json-ld-rdf-rdfa.rst.html
